### ISSUE TITLE
Chrome OS touchscreen detection failure

### ISSUE THREAD

**Issue by lengau** [rafgraph/detect-it#17]
detect-it fails to detect touchscreen Chrome OS devices (in my case a Pixel Slate) as a touchscreen. Detected data doesn't vary between laptop mode and tablet mode:

`deviceType: mouseOnly
passiveEvents: true
hasMouse: true
hasTouch: false
primaryInput: mouse`

However, detect-touch succeeds:

    Touch interface test results:
    Test for the standard W3C Touch Events API (vast majority of touch devices):
    'ontouchstart' in window: false
    Tests for number of touch points (required to detect Microsoft's Pointer Events API running on a touch device, however, devices not implmenting Pointer Events may also indicate this):
    window.navigator.maxTouchPoints: 10
    window.navigator.msMaxTouchPoints: undefined
    Test for Firefox's legacy touch implemntation (which is now obsolete):
    window.DocumentTouch && document instanceof DocumentTouch: undefined

**Comment by rafrex** [comment]
Thanks for results. I'm pretty sure this is a case where the browser (is it Chrome or something else?) has implemented the PointerEvents api but not the TouchEvents api. The current version of `detect-it` doesn't use PointerEvents because for a while there wasn't enough browser support, but times have changed and I will be adding PointerEvents support to the detection.

v1 of `detect-it` does support PointerEvents and should be accurate, so you can use that in the meantime [v1 live section](http://detect-it-v1.rafrex.com)

**Comment by rafgraph** [comment]
@lengau `detect-it` v4 is in pre-release and includes PointerEvents as well as improved device detection. Try it out with `npm install --save detect-it@next` or view the live detection test at https://detect-it.rafgraph.dev

**Comment by lengau** [comment]
Sorry for the delayed response - yes, dev version works perfectly on CrOS now.

For the record for anyone looking: Chrome OS touchscreen device with keyboard:

![image](https://user-images.githubusercontent.com/4305943/101696041-18e3dd00-3a3b-11eb-93ea-988c7ad41078.png)

Without keyboard:

![image](https://user-images.githubusercontent.com/4305943/101696163-4b8dd580-3a3b-11eb-9106-eaa921c02069.png)

**Comment by rafgraph** [comment]
v4 released 🎉
